schedulers:
  - name: sarathi_256
    scheduler: sarathi
    chunk_size: 256
    batch_size: 128
  - name: sarathi_512
    scheduler: sarathi
    chunk_size: 512
    batch_size: 128
  - name: sarathi_1024
    scheduler: sarathi
    chunk_size: 1024
    batch_size: 128

traces:
  - name: chat
    trace_file: "./data/processed_traces/sharegpt_8k_filtered_stats_llama2_tokenizer.csv"
    max_seq_len: 8192
    num_requests: 1024
    start_qps: 4 # this param is ignored in isoqps runs

parallel_spec:
  - name: tp_1
    tp_dimension: 1
    pp_dimension: 1

models:
  - name: mistral-7b
    identifier: mistralai/Mistral-7B-Instruct-v0.2
    parallel_specs: ["tp_1"]
    scheduler_specs: null # usee all
    traces: null # use all
