schedulers:
  - name: vllm
    scheduler: vllm
    batch_size: 128

traces:
  - name: chat
    trace_file: "./data/processed_traces/sharegpt_8k_filtered_stats_llama2_tokenizer.csv"
    max_seq_len: 8192
    num_requests: 2048
    start_qps: 1.6

parallel_spec:
  - name: tp_8
    tp_dimension: 8
    pp_dimension: 1

models:
  - name: falcon-180b
    identifier: tiiuae/falcon-180B
    parallel_specs: ["tp_8"]
    scheduler_specs: null # usee all
    traces: null # use all
